pidev_site_homepage:
    pattern:  /index
    defaults: { _controller: PidevSiteBundle:Default:index }

pidev_site_details:
    pattern:  /details
    defaults: { _controller: PidevSiteBundle:Default:details }
    
pidev_site_liste:
    pattern:  /liste
    defaults: { _controller: PidevSiteBundle:Default:liste }
    
