pidev_site:
    resource: "@PidevSiteBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin
    
Site:
    resource: "@PidevSiteBundle/Resources/config/routing.yml"
    prefix:   /Site

