Commentaire:
    type: entity
    table: commentaire
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        contenu:
            type: string
            length: 1000
            fixed: false
            nullable: false
        date:
            type: integer
            unsigned: false
            nullable: false
        idRestaurant:
            type: integer
            unsigned: false
            nullable: false
            column: id_restaurant
        idClient:
            type: integer
            unsigned: false
            nullable: false
            column: id_client
    lifecycleCallbacks: {  }
